/**
 * Generated by scripts/generate-property-art.mjs — do not edit by hand.
 * Regenerate with `npm run art`.
 */

export type ArtKind =
  | "exterior"
  | "interior"
  | "terrace"
  | "amenity"
  | "aerial"
  | "construction"
  | "plan";

export interface ArtImage {
  id: string;
  kind: ArtKind;
  src: string;
  alt: string;
}

export const ART: readonly ArtImage[] = [
  {
    "id": "azure-exterior",
    "kind": "exterior",
    "src": "/art/azure-exterior.svg",
    "alt": "Seafront residential tower at dusk with lit windows reflected in the water"
  },
  {
    "id": "azure-coast",
    "kind": "aerial",
    "src": "/art/azure-coast.svg",
    "alt": "Coastal hillside with terraced residences descending to a promenade at dusk"
  },
  {
    "id": "azure-terrace",
    "kind": "terrace",
    "src": "/art/azure-terrace.svg",
    "alt": "Terrace with glass balustrade facing the sea at golden hour"
  },
  {
    "id": "azure-living",
    "kind": "interior",
    "src": "/art/azure-living.svg",
    "alt": "Living room with warm lamps and a dusk sea view through floor-to-ceiling glass"
  },
  {
    "id": "azure-pool",
    "kind": "amenity",
    "src": "/art/azure-pool.svg",
    "alt": "Rooftop infinity pool at dusk overlooking a city skyline"
  },
  {
    "id": "park-exterior",
    "kind": "exterior",
    "src": "/art/park-exterior.svg",
    "alt": "Manhattan residential tower at night, windows glowing warm"
  },
  {
    "id": "park-penthouse",
    "kind": "interior",
    "src": "/art/park-penthouse.svg",
    "alt": "Penthouse interior in silhouette against a night city skyline"
  },
  {
    "id": "park-bedroom",
    "kind": "interior",
    "src": "/art/park-bedroom.svg",
    "alt": "Bedroom in soft morning light with bedside lamps"
  },
  {
    "id": "park-lobby",
    "kind": "amenity",
    "src": "/art/park-lobby.svg",
    "alt": "Double-height lobby with warm slatted wall and glass entrance at dusk"
  },
  {
    "id": "marina-villa",
    "kind": "exterior",
    "src": "/art/marina-villa.svg",
    "alt": "Modern villa at dusk with glowing glass walls and an infinity pool"
  },
  {
    "id": "marina-villa-golden",
    "kind": "exterior",
    "src": "/art/marina-villa-golden.svg",
    "alt": "Villa exterior at golden hour with cypress silhouettes"
  },
  {
    "id": "marina-kitchen",
    "kind": "interior",
    "src": "/art/marina-kitchen.svg",
    "alt": "Kitchen island under three warm pendant lights"
  },
  {
    "id": "marina-terrace",
    "kind": "terrace",
    "src": "/art/marina-terrace.svg",
    "alt": "Sea-view terrace at dusk with a candle-lit table"
  },
  {
    "id": "grove-aerial",
    "kind": "aerial",
    "src": "/art/grove-aerial.svg",
    "alt": "Aerial view of a residential development at dusk, streets glowing"
  },
  {
    "id": "grove-exterior",
    "kind": "exterior",
    "src": "/art/grove-exterior.svg",
    "alt": "Residential quarter at golden hour with warm lit facades"
  },
  {
    "id": "grove-construction",
    "kind": "construction",
    "src": "/art/grove-construction.svg",
    "alt": "Construction site at dawn with tower cranes and work lights"
  },
  {
    "id": "grove-living",
    "kind": "interior",
    "src": "/art/grove-living.svg",
    "alt": "Show-apartment living room with a city view at dusk"
  },
  {
    "id": "grove-plan",
    "kind": "plan",
    "src": "/art/grove-plan.svg",
    "alt": "Apartment floor plan drawn in light lines on deep blue paper"
  },
  {
    "id": "meridian-exterior",
    "kind": "exterior",
    "src": "/art/meridian-exterior.svg",
    "alt": "Glass tower reflecting the sunset in its curtain wall"
  },
  {
    "id": "meridian-skyline",
    "kind": "exterior",
    "src": "/art/meridian-skyline.svg",
    "alt": "Waterfront skyline at dusk with reflections"
  },
  {
    "id": "meridian-pool",
    "kind": "amenity",
    "src": "/art/meridian-pool.svg",
    "alt": "Rooftop pool at golden hour above the skyline"
  },
  {
    "id": "villa-night",
    "kind": "exterior",
    "src": "/art/villa-night.svg",
    "alt": "Villa at night, interior light spilling onto the pool"
  },
  {
    "id": "coast-marine",
    "kind": "aerial",
    "src": "/art/coast-marine.svg",
    "alt": "Misty morning coastal town by a calm sea"
  },
  {
    "id": "tower-marine",
    "kind": "exterior",
    "src": "/art/tower-marine.svg",
    "alt": "Seafront towers on a soft misty morning"
  },
  {
    "id": "interior-bed-2",
    "kind": "interior",
    "src": "/art/interior-bed-2.svg",
    "alt": "Calm bedroom with sea light"
  },
  {
    "id": "interior-living-2",
    "kind": "interior",
    "src": "/art/interior-living-2.svg",
    "alt": "Living room at dusk with pendant lights"
  },
  {
    "id": "construction-2",
    "kind": "construction",
    "src": "/art/construction-2.svg",
    "alt": "Concrete frame and cranes against a dawn sky"
  },
  {
    "id": "penthouse-2",
    "kind": "interior",
    "src": "/art/penthouse-2.svg",
    "alt": "Night penthouse with city lights reflected in the floor"
  },
  {
    "id": "lobby-2",
    "kind": "amenity",
    "src": "/art/lobby-2.svg",
    "alt": "Hotel lobby with warm pendants and city dusk beyond"
  },
  {
    "id": "aerial-2",
    "kind": "aerial",
    "src": "/art/aerial-2.svg",
    "alt": "Development masterplan seen from above at dusk"
  },
  {
    "id": "office-2",
    "kind": "exterior",
    "src": "/art/office-2.svg",
    "alt": "Office tower catching the last light"
  },
  {
    "id": "terrace-2",
    "kind": "terrace",
    "src": "/art/terrace-2.svg",
    "alt": "Morning terrace over a calm sea"
  },
  {
    "id": "plan-2",
    "kind": "plan",
    "src": "/art/plan-2.svg",
    "alt": "Floor plan sheet with balcony detail"
  }
];

export const artById = (id: string): ArtImage => {
  const found = ART.find((image) => image.id === id);
  if (!found) throw new Error(`Unknown art id: ${id}`);
  return found;
};
