// PROPX · official market indicators — daily snapshot.
//
// mergeSnapshot(prev, results, now) is the single place that decides what
// the site shows:
//   · a source that answered and validated → its fresh value, checkedAt=now;
//   · a source that failed → the previous value KEPT but marked stale, with
//     the failure reason and the attempt time (never silently "refreshed");
//   · a source that failed and has no previous value → absent, so the UI
//     falls back to its own dated, published figures.
// An index period never moves backwards: a response older than what is
// already published is rejected as a failure (wrong or dead series).

'use strict';

const KEYS = ['boiRate', 'newHomesIndex', 'dwellingsIndex'];
const RUNTIME_FIELDS = ['checkedAt', 'stale', 'lastError', 'lastAttemptAt', 'seriesChangedFrom'];

const periodNum = (p) => (p && p.year ? p.year * 12 + p.month : 0);

function mergeSnapshot(prev, results, now) {
  const at = typeof now === 'string' ? now : now.toISOString();
  const prevInd = (prev && prev.indicators) || {};
  const out = { schema: 1, syncedAt: at, ok: true, indicators: {}, failures: [] };
  for (const key of KEYS) {
    const r = results[key];
    const p = prevInd[key];
    let error = null;
    if (!r) error = 'not attempted';
    else if (!r.ok) error = r.error || 'failed';
    else if (p && p.period && r.data.period && periodNum(r.data.period) < periodNum(p.period)) {
      error = `period went backwards (${r.data.period.year}-${r.data.period.month} < ` +
        `${p.period.year}-${p.period.month}) — rejected`;
    }
    if (!error) {
      const v = { ...r.data, checkedAt: at, stale: false };
      if (p && p.series && r.data.series && p.series.code !== r.data.series.code) v.seriesChangedFrom = p.series.code;
      out.indicators[key] = v;
      continue;
    }
    out.ok = false;
    out.failures.push({ key, error });
    if (p) out.indicators[key] = { ...p, stale: true, lastError: error, lastAttemptAt: at };
  }
  return out;
}

/** The data-only part (no run times) — its hash changes only when data does. */
function dataPayload(snapshot) {
  const ind = {};
  for (const [k, v] of Object.entries((snapshot && snapshot.indicators) || {})) {
    const d = { ...v };
    for (const f of RUNTIME_FIELDS) delete d[f];
    ind[k] = d;
  }
  return ind;
}

function toJs(snapshot) {
  // external script, but escape '<' anyway so the payload can never be
  // mistaken for markup if the file is ever inlined (standalone build)
  const json = JSON.stringify(snapshot).replace(/</g, '\\u003c');
  return '/* generated by scripts/market-sync.js — do not edit by hand */\n' +
    `window.PROPX_MARKET=${json};\n`;
}

const EMPTY = Object.freeze({ schema: 1, syncedAt: null, ok: false, indicators: {}, failures: [] });

module.exports = { mergeSnapshot, dataPayload, toJs, KEYS, EMPTY };
